name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: echo swift build -v
    - name: Run tests
      run: echo swift test -v
    - name: Test 2
      run: git clone https://github.com/mac-ci-jpg/test2.git && cd test2 && bash test.sh
